name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1

    # Looking for caches
    #- uses: actions/cache@v1
    #  with:
    #    path: ~/.gradle/caches
    #    key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle') }}
    #    restore-keys: |
    #      ${{ runner.os }}-gradle-
    
    # Setting up JDK
    - name: set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8

    # The following generates a debug APK
    - name: Build with Gradle
      run: ./gradlew assembleDebug
